---
title: "Movie Recommendation System"
author: "Silas Mwandikwa"
date: "2023-08-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
We will be building a movie recommendation system for movie sites or applications such as Netflix

We load the libraries first

```{r}

library(recommenderlab)
library(data.table)
library(reshape2)
library(ggplot2)
```

## Loading the data

```{r}

movie_data <- read.csv("IMDB-Dataset/movies.csv",stringsAsFactors = FALSE) #Letting strings remain strings
rating_data <- read.csv("IMDB-Dataset/ratings.csv")
str(movie_data)
```

```{r}
summary(movie_data)
library(tidyverse)
```


```{r}
glimpse(movie_data)
```

```{r}
head(movie_data)
```


```{r}
tail(movie_data)
```


```{r}
summary(rating_data)
```

```{r}
movie_genre <- as.data.frame(movie_data$genres, stringsAsFactors = FALSE)
# We are combining movie_data and the genres to one data frame as strings
library(data.table)
movie_genre2 <- as.data.frame(tstrsplit(movie_genre[ ,1], '[ | ]',
                                        type.convert = TRUE),
                              stringsAsFactors=FALSE)
# Splitting the strings in the movie_genre df we just created, and ensuring strings 
#aren't changed to factors
colnames(movie_genre2) <- c(1:10) # We'll have 10 columns
glimpse(movie_genre2)
list_genre <- c("Action", "Adventure", "Animation", "Children", "Comedy",
                "Crime", "Documentary", "Drama", "Fantasy", "Film-Noir", "Horror",
                "Musical", "Mystery", "Romance", "Sci-Fi", "Thriller", "War",
                "Western")

genre_mat1 <- matrix(0,10330,18) # create a matrix based on our number of rows and #cols, remember the columns are the different genres we just listed
genre_mat1[1, ] <- list_genre #ensuring to make it two dimensional with a focus on #first column
colnames(genre_mat1) <- list_genre

for (index in 1:nrow(movie_genre2)) {
  for (col in 1:ncol(movie_genre2)) {
    gen_col = which(genre_mat1[1, ] == movie_genre2[index,col])
    genre_mat1[index+1,gen_col] <- 1
  }
}
# Basically looking at the data from both movie_genre2 and genre_mat1 and comparing #what matches in both datasets, remember our objective

genre_mat2 <-  as.data.frame(genre_mat1[-1, ], stringsAsFactors=FALSE)
#Remove first row, which was the genre list

for (col in 1:ncol(genre_mat2)) {
  genre_mat2[,col] <- as.integer(genre_mat2[,col]) #convert from characters to integers
}

str(genre_mat2)
```


```{r}
SearchMatrix <- cbind(movie_data[ ,1:2], genre_mat2[]) #Basically binding data in #movie_data df with a focus on the title and genre columns to the genre_mat2 
head(SearchMatrix)
#As you can see from the matrix created for instance first output of Toy Story, it #now tells us exactly which genres match with the movie, it is for kids, its #adventure, animation, but 0 value for documentary since Toy Story is not a #documentary
```

```{r}
ratingMatrix <- dcast(rating_data, userId~movieId, value.var = 'rating',
                      na.rm=FALSE)
ratingMatrix <- as.matrix(ratingMatrix[,-1]) #remove userids, coz they are in the
#first column, so minus 1
#Convert rating matrix into a recommenderlab sparse matrix
ratingMatrix <- as(ratingMatrix, "realRatingMatrix")
ratingMatrix
```

```{r}
recommendation_model <- recommenderRegistry$get_entries(dataType = "realRatingMatrix")
names(recommendation_model)
```

```{r}
lapply(recommendation_model, "[[", "description")
```


```{r}
recommendation_model$IBCF_realRatingMatrix$parameters
```


```{r}
similarity_mat <- similarity(ratingMatrix[1:4, ],
                             method = "cosine",
                             which = "users")
#Creating a similarity matrix based on what different users watch and the films themselves
as.matrix(similarity_mat)

image(as.matrix(similarity_mat), main = "User's Similarities")

movie_similarity <- similarity(ratingMatrix[, 1:4], method = "cosine",
                               which = "items")

as.matrix(movie_similarity)

image(as.matrix(movie_similarity), main = "Movies Similarity")
```


```{r}
rating_values <- as.vector(ratingMatrix@data) # extracting unique ratings
unique(rating_values)

#Creating a table of ratings to display our unique values
Table_of_Ratings <- table(rating_values) # Creating a count of movie ratings
Table_of_Ratings
```


```{r}
library(ggplot2)
movie_views <- colCounts(ratingMatrix) # Count the views for each film
table_views <- data.frame(movie = names(movie_views),
                          views = movie_views) # Create data frame for views
table_views <- table_views[order(table_views$views,
                                 decreasing = TRUE), ] # Sorting by the number of views from largest to smallest

table_views$title <- NA
for (index in 1:10325) {
  table_views[index,3] <- as.character(subset(movie_data, 
                                              movie_data$movieId ==
                                                table_views[index,1])$title)
}
table_views[1:6,] #Pulp fiction is the movie with most views, no surprise there
```


```{r}
ggplot(table_views[1:6, ], aes(x = title, y = views)) +
  geom_bar(stat = "identity", fill = 'steelblue') +
  geom_text(aes(label = views), vjust=-0.3, size=3.5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  
  ggtitle("Total Views of the Top Films")
```


```{r}
image(ratingMatrix[1:25, 1:25], axes = FALSE, main = "Heatmap of the First 25 rows and columns")
```


```{r}
movie_ratings <- ratingMatrix[rowCounts(ratingMatrix) > 50,
                              colCounts(ratingMatrix) > 50]

movie_ratings
```

```{r}
minimum_movies <- quantile(rowCounts(movie_ratings), 0.98)
minimum_users <- quantile(colCounts(movie_ratings), 0.98)
image(movie_ratings[rowCounts(movie_ratings) > minimum_movies,
                    colCounts(movie_ratings) > minimum_users],
      main = "Heatmap of the top Users and Movies")
```


```{r}
average_ratings <- rowMeans(movie_ratings)
qplot(average_ratings, fill=I("steelblue"), col=I("red")) + 
  ggtitle("Distribution of the average rating per user")
```


```{r}
normalized_ratings <- normalize(movie_ratings)
sum(rowMeans(normalized_ratings) > 0.00001)

image(normalized_ratings[rowCounts(normalized_ratings) > minimum_movies,
                         colCounts(normalized_ratings) > minimum_users],
      main = "Normalized Ratings for Top Users")
```


```{r}
binary_minimum_movies <- quantile(rowCounts(movie_ratings), 0.95)
binary_minimum_users <- quantile(rowCounts(movie_ratings), 0.95)

good_rated_films <- binarize(movie_ratings, minRating =3)
image(good_rated_films[rowCounts(movie_ratings) > binary_minimum_movies,
                       rowCounts(movie_ratings) > binary_minimum_users],
      main = "Heatmap of the top users and movies")
```


```{r}
sampled_data <- sample(x = c(TRUE, FALSE),
                       size = nrow(movie_ratings),
                       replace = TRUE,
                       prob = c(0.8, 0.2))

trained_data <- movie_ratings[sampled_data, ]
testing_data <- movie_ratings[!sampled_data, ]
```


```{r}
recommendation_system <- recommenderRegistry$get_entries(dataType
                                                         ="realRatingMatrix")
recommendation_system$IBCF_realRatingMatrix$parameters

recommen_model <- Recommender(data = trained_data,
                              method = "IBCF",
                              parameter = list(k = 30))
recommen_model
class(recommen_model)
```


```{r}
model_info <- getModel(recommen_model)
class(model_info$sim)
dim(model_info$sim)
top_items <- 20
image(model_info$sim[1:top_items, 1:top_items],
      main = "Heatmap of the first rows and columns")
```


```{r}
library(c(flexdashboard, tidyverse, highcharter, gt, htmltools, virirdis))

custom_colors <- viridis::magma(n = 15)

sum_rows <- rowSums(model_info$sim > 0)
table(sum_rows)

sum_cols <- colSums(model_info$sim > 0)
qplot(sum_cols, fill=I("steelblue"), col=I("red")) + 
  ggtitle("Distribution of Column Count") %>% 
  hchart('column', hcaes(x = sum_cols, y = sum_rows, color = custom_colors)) %>% 
  hc_add_theme(hc_theme_google()) %>% 
  hc_tooltip(pointFormat = '<b>Number of sum_cols: </b> {point.y} <br>') %>% 
  hc_title(text = 'Column Count Distribution',
           style = list(fontSize = '25px', fontWeight = 'bold')) %>% 
  hc_subtitle(text = 'Against sum of Rows',
              style = list(fontSize = '16px')) %>% 
  hc_credits(enabled = TRUE, text = '@MwandikwaSilas')
```


```{r}
top_recommendations <- 10 #the number of items to recommend to each user
predicted_recommendations <- predict(object = recommen_model,
                                     newdata = testing_data,
                                     n = top_recommendations)

predicted_recommendations
```


```{r}
user1 <- predicted_recommendations@items[[1]] #recommendation for the first user
movies_user1 <- predicted_recommendations@itemLabels[user1]
movies_user2 <- movies_user1

for (index in 1:10) {
  movies_user2[index] <- as.character(subset(movie_data,
                                             movie_data$movieId ==
                                               movies_user1[index])$title)
}

movies_user2
```


```{r}
recommendation_matrix <- sapply(predicted_recommendations@items,
                                function(x){ as.integer(colnames(movie_ratings)[x])}) #matrix with recommendations for each user

recommendation_matrix[,1:4]
```

